name: docker-build

on:
  pull_request:
    branches:
      - 'master'

jobs:
  steam-gameserver-token-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: steam-gameserver-token-api
        uses: docker/build-push-action@v1
        with:
          push: false
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: npflan/steam-gameserver-token-api
          tags: latest
